### ISSUE TITLE
A few things

### ISSUE THREAD

**Issue by Fortist** [Silly511/Resonant-Toolbox#2]
1)Configs - enable disable features or things, like disabling the Arrow thing for swords, disabling sapphire generation. etc etc
2)Bow - for the arrow thing
3)Configurable power usage - 2k per tick isnt a lot and/or 600m is too much
4)And/or Damage increases power usage - like RA armor does.
5) Visual RF damage bars - so you can see how much RF is left without having to open your inventory, or if you have a Armor HUD.

**Comment by Fadenfire** [comment]
1) There is already a config file where you can configure power usage, disable/enable the different tools and sapphire ore gen.
2) No. I might add a config option for this but probably not. The whole point of shooting the arrow from the sword was so that you didn't have to use an extra hotbar slot for a bow.
3) Same answer as number one.
4) Maybe.
5) I am planning on making this a config option(by default enabled), however don't expect it too soon.

**Comment by Fortist** [comment]
Oh, I didnt see the file because it was under your name.
Thats kinda dumb.
Also, I just prefer bows since shooting arrows with a sword is dumb.

**Comment by Fadenfire** [comment]
Well I ment the arrows to be like blasts of energy not actually arrows, because one they look very different than regular arrows and two they don't stick in the ground. I just said arrows on the wiki because I didn't know what else to say. But if you really want me to I'll add a config option to add a bow.
